### ISSUE TITLE
Roadmap to unify confidential images

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/attestation-agent#128]
This road map tracks the issue mentioned in https://github.com/confidential-containers/attestation-agent/issues/113.

#### Stage 1

- [ ] Have a universal format of `AnnotationPacket`
https://github.com/confidential-containers/attestation-agent/pull/117
- [ ] implement cc-kbc to handle the image-layer
- [ ] implement sample-kbc to handle the image-layer, or directly abondon this module
- [ ] implement offline-fs-kbc to handle the image-layer
- [ ] implement offline-sev-kbc to handle the image-layer
- [ ] implement online-sev-kbc to handle the image-layer
- [ ] implement eaa-sev-kbc to handle the image-layer
- [ ] implement a single key-provider

#### Stage 2

- [ ] Prepare test images using new format of `AnnotationPacket` for kata-cc and enclave-cc

**Comment by Xynnn007** [comment]
Add more for test cases
